### ISSUE TITLE
Plugins ads invisible sidebar

### ISSUE THREAD

**Issue by silveltman** [mycast-ai/payload-plugin-ai-completions#3]
On collection where this plugin is enabled, a sidebar is always added in the admin ui, even when it does not contain any values. This takes up valueable space. See screenshot:

![Screenshot 2023-10-10 at 20 20 43](https://github.com/mycast-ai/payload-plugin-ai-completions/assets/52583398/060c6621-5d5c-44f8-b4aa-bacb7eacff3a)

**Comment by silveltman** [comment]
In looked at the sourcode and found this field/function:
```
export const generateSidebarFields = ({
  collectionConfig,
  pluginOptions,
  collectionOptions,
}: {
  collectionConfig: CollectionConfig
  pluginOptions: PluginOptions
  collectionOptions: CollectionOptions
}): UIField => {
  return {
    type: 'ui',
    name: 'name',
    admin: {
      position: 'sidebar',
      components: {
        Field: () => AiCompletionsDashboard({ collectionConfig, pluginOptions, collectionOptions }),
      },
    },
  }
```

Is the plugin supposed to create a field in the sidebar? It does not do that on my dashbaord.

**Comment by filipzava** [comment]
Hi, please try this settings: 
You must explicitly allow it. 

```javascript
aiCompletions({
    enabled: true,
    dashboard: {
        enabled: true,
        completeAllButton: true,
        minimalisticUi: true,
    },
 ....
})
```
